name: multimodular_app
environment:
  sdk: ">=3.11.3 <4.0.0"
dev_dependencies:
  melos: ^7.5.1
melos:
  useRootAsPackage: true
  categories:
    app:
      - "."
    packages:
      - core/**
      - features/**
      - features/auth/**
