name: multimodular_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  app_settings:
    path: features/settings/app_settings
  datastore:
    path: core/datastore

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: 5.9.2
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  melos: ^7.5.1
  injectable_generator: ^2.12.1
  json_serializable: ^6.13.1
  build_runner: ^2.13.1

flutter:
  uses-material-design: true

melos:
  useRootAsPackage: true
  command:
    bootstrap:
      environment:
        sdk: ^3.11.3
        flutter: ">=3.0.0 <4.0.0"
      dependencies:
        dio: 5.9.2
        get_it: ^9.2.1
        injectable: ^2.7.1+4
        json_annotation: ^4.11.0
        cupertino_icons: ^1.0.8
        pretty_dio_logger: ^1.4.0
        retrofit: ^4.9.2
        dartz: ^0.10.1

      dev_dependencies:
        injectable_generator: ^2.12.1
        json_serializable: ^6.13.1
        build_runner: ^2.13.1
        retrofit_generator: ^10.2.5
        flutter_lints: ^6.0.0

        flutter_test:
          sdk: flutter

      hooks:
        post: dart run build_runner build -d
  scripts:
    hello:
      name: hey
      description: Greet the world
      run: echo $GREETING World
      env:
        GREETING: Hey
    upgrade:
      run: flutter pub outdated && flutter pub upgrade --major-versions
    test:
      run: melos exec --concurrency=1 -- flutter test
    cbs:
      run: melos clean && melos bs

workspace:
  - core/data
  - core/datastore
  - core/domain
  - core/presentation
  - features/auth/login
  - features/auth/register
  - features/home/main
  - features/movies
  - features/settings/app_settings
  - features/settings/profile
